// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkblawrtzbkfpklgacqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrYmxhd3J0emJrZnBrbGdhY3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDUzMjUsImV4cCI6MjA2NTg4MTMyNX0.dICd7yi9aRQxISsTPDp4I0qB6M9viqUHNBWS4R1JLPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);